source "https://rubygems.org"
gem "jekyll", "~> 3.8.5"
gem "jekyll-remote-theme"
gem "just-the-docs"
gem "github-pages", group: :jekyll_plugins
gem "activesupport", ">= 4.1.11"

group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jekyll-feed"
  gem "jemoji"
  gem "jekyll-include-cache"
  gem "jekyll-algolia"
end

gem "tzinfo-data"
gem "wdm", "~> 0.1.0" if Gem.win_platform?
